version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/mydatabase

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4043434
    ports:
      - "15432:5432"
    restart: unless-stopped